import os

STORE_PATH = "store.json"
DISPLAY_WIDTH = 250
DISPLAY_HEIGHT = 122
OPEN_WEATHER_TOKEN = os.environ.get("OPEN_WEATHER_TOKEN")
COORDINATES = os.environ.get("COORDINATES")  # format is <lat>,<lng>
assert COORDINATES is not None
LAT, LON = COORDINATES.split(",")
RESPONSE_PATH = os.getenv("RESPONSE_PATH")
RENDER_INTERVAL = int(os.environ.get("RENDER_INTERVAL", "600"))
WEATHER_REFRESH_INTERVAL = int(os.environ.get("WEATHER_REFRESH_INTERVAL", "600"))
EXAMPLE_RESPONSE = os.getenv("EXAMPLE_RESPONSE")
